---Adding team names according to stadiums 
UPDATE matches
SET "TEAM STADIUM" = CASE 
    WHEN "STADIUM" ='Emirates Stadium'
THEN  'ARSENAL'
    WHEN "STADIUM" = 'Villa Park'      
THEN  'ASTON VILA'
    WHEN "STADIUM" = 'Gtech Community Stadium' 
THEN 'BRENTFORD'
    WHEN "STADIUM" = 'Stamford Bridge' 
THEN 'CHELSEA'
    WHEN "STADIUM" = 'Selhurst Park'   
THEN 'CRYSTAL PALACE'
    WHEN "STADIUM" = 'Goodison Park'   
THEN 'EVERTON'
    WHEN "STADIUM" = 'Elland Road'      
THEN 'LEEDS UNITED'
    WHEN "STADIUM" = 'The King Power Stadium' 
THEN 'LECIESTER UNITED'
    WHEN "STADIUM" = 'Old Trafford'     
THEN 'MANCHESTER UNITED'
    WHEN "STADIUM" = 'St. Mary''s Stadium' 
THEN 'SOUTHAMPTON'
    WHEN "STADIUM" = 'Amex Stadium'     
THEN 'BRIGTHON'
    WHEN "STADIUM" = 'Tottenham Hotspur Stadium' 
THEN 'TOTTENHAM FC'
    WHEN "STADIUM" = 'Vitality Stadium' 
THEN 'BOURNEMOUTH'
    WHEN "STADIUM" = 'Craven Cottage' 
THEN 'FULHAM UNITED'
    WHEN "STADIUM" = 'Anfield'       
THEN 'LIVERPOOL'
    WHEN "STADIUM" = 'Molineux'       
THEN 'WOLVES FC'
    WHEN "STADIUM" = 'The City Ground' 
THEN 'NOTTINGHAM FOREST'
    WHEN "STADIUM" = 'St James'' Park, Newcastle' 
THEN  'NEWCASTLE UNITED'
    WHEN "STADIUM" = 'London Stadium' 
THEN 'WESTHAM UNITED'
    WHEN "STADIUM" = 'Etihad Stadium' 
THEN 'MANCHESTER CITY'
    WHEN "STADIUM" = 'Vicarage Road' 
THEN 'WATFORD FC'
    WHEN "STADIUM" = 'Carrow Road'   
THEN 'NORWICH CITY'
    WHEN "STADIUM" =  'Turf Moor'    
THEN 'BURNLEY FC' 
END;

